// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * Assertion defines a response assertion declared via # @assert.
 */
export interface Assertion {
    /**
     * "status", "body.$.id", "header.Content-Type", "duration", "size"
     */
    "Target": string;

    /**
     * "==", "!=", "<", ">", "<=", ">=", "contains", "matches", "exists", "!exists"
     */
    "Operator": string;

    /**
     * "201", "Alice", "json"
     */
    "Expected": string;

    /**
     * original text: "status == 201"
     */
    "Raw": string;
}

/**
 * AssertionResult holds the outcome of evaluating one assertion.
 */
export interface AssertionResult {
    "Assertion": Assertion;
    "Passed": boolean;

    /**
     * the value that was tested
     */
    "Actual": string;

    /**
     * non-empty if evaluation itself failed
     */
    "Error": string;
}

export interface Environment {
    "Name": string;
    "Variables": { [_ in string]?: string } | null;
}

export interface EnvironmentFile {
    "Shared": { [_ in string]?: string } | null;
    "Environments": { [_ in string]?: Environment } | null;
}

export interface Header {
    "Key": string;
    "Value": string;
}

export interface Request {
    "Name": string;
    "Method": string;
    "URL": string;
    "HTTPVersion": string;
    "Headers": Header[] | null;
    "Body": string;
    "BodyFile": string;
    "Metadata": RequestMetadata;
    "Assertions": Assertion[] | null;
    "PreRequestScript": string;
    "PostResponseScript": string;
    "SourceFile": string;
    "SourceLine": number;
}

export interface RequestMetadata {
    "NoRedirect": boolean;
    "NoCookieJar": boolean;
    "Timeout": time$0.Duration;
    "ConnTimeout": time$0.Duration;

    /**
     * skip TLS verification
     */
    "Insecure": boolean;

    /**
     * proxy URL (http://proxy:port)
     */
    "Proxy": string;
}

export interface Response {
    "StatusCode": number;
    "Status": string;
    "Headers": Header[] | null;
    "Body": string | null;
    "ContentType": string;
    "Timing": ResponseTiming;
    "Request": Request | null;
    "Timestamp": time$0.Time;
    "AssertionResults": AssertionResult[] | null;

    /**
     * non-empty if post-response script failed
     */
    "ScriptError": string;
}

export interface ResponseTiming {
    "DNS": time$0.Duration;
    "Connect": time$0.Duration;
    "TLS": time$0.Duration;
    "TTFB": time$0.Duration;
    "Total": time$0.Duration;
    "BodyRead": time$0.Duration;
}
