// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CollectionService wraps parser and writer packages for collection management
 * in the Wails GUI.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * CreateDirectory creates a new directory under the root.
 */
export function CreateDirectory(root: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(1226217231, root, name);
}

/**
 * CreateFile creates a new .http file at the specified relative path.
 */
export function CreateFile(root: string, relPath: string): $CancellablePromise<void> {
    return $Call.ByID(39825522, root, relPath);
}

/**
 * CreateRequest inserts a new request into the specified .http file.
 */
export function CreateRequest(filePath: string, req: model$0.Request): $CancellablePromise<void> {
    return $Call.ByID(1078128125, filePath, req);
}

/**
 * DeleteEntry deletes a file or directory.
 */
export function DeleteEntry(root: string, relPath: string): $CancellablePromise<void> {
    return $Call.ByID(420902917, root, relPath);
}

/**
 * DeleteRequest removes a request from the file.
 */
export function DeleteRequest(filePath: string, req: model$0.Request): $CancellablePromise<void> {
    return $Call.ByID(2118862148, filePath, req);
}

/**
 * DuplicateRequest duplicates a request to the specified destination file.
 */
export function DuplicateRequest(req: model$0.Request, dstFile: string): $CancellablePromise<void> {
    return $Call.ByID(4161071702, req, dstFile);
}

/**
 * GetRequests parses a single .http file and returns its requests.
 */
export function GetRequests(filePath: string): $CancellablePromise<model$0.Request[] | null> {
    return $Call.ByID(2326330978, filePath);
}

/**
 * LoadCollection loads all .http files from the root directory.
 */
export function LoadCollection(dir: string): $CancellablePromise<model$0.Collection | null> {
    return $Call.ByID(2915986944, dir);
}

/**
 * RenameEntry renames a file or directory.
 */
export function RenameEntry(root: string, oldRelPath: string, newRelPath: string): $CancellablePromise<void> {
    return $Call.ByID(3927927114, root, oldRelPath, newRelPath);
}

/**
 * UpdateRequest updates an existing request in the file.
 */
export function UpdateRequest(filePath: string, old: model$0.Request, updated: model$0.Request): $CancellablePromise<void> {
    return $Call.ByID(4085046742, filePath, old, updated);
}
