// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EnvironmentService wraps environment parsing for the Wails GUI.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * GetCurrentEnv returns the currently selected environment name.
 */
export function GetCurrentEnv(): $CancellablePromise<string> {
    return $Call.ByID(4141006533);
}

/**
 * ListEnvironmentNames returns a sorted list of environment names available in dir.
 */
export function ListEnvironmentNames(dir: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(3498913492, dir);
}

/**
 * LoadEnvironments loads the environment file from the given directory.
 * Returns the full EnvironmentFile with shared vars and per-env vars.
 */
export function LoadEnvironments(dir: string): $CancellablePromise<model$0.EnvironmentFile | null> {
    return $Call.ByID(1785002525, dir);
}

/**
 * ResolveVars returns all resolved variables for the given environment.
 * Merges shared vars with env-specific vars.
 */
export function ResolveVars(dir: string, envName: string): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(2349494175, dir, envName);
}

/**
 * SetCurrentEnv sets the active environment.
 */
export function SetCurrentEnv(name: string): $CancellablePromise<void> {
    return $Call.ByID(4068143953, name);
}
