// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExporterService wraps the exporter package for Wails GUI consumption.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * AvailableLanguages returns the sorted list of supported code generation language names.
 */
export function AvailableLanguages(): $CancellablePromise<string[] | null> {
    return $Call.ByID(91317091);
}

/**
 * GenerateCode generates code for the given request in the specified language.
 * Language is matched case-insensitively against available generator names
 * (e.g. "Python", "JavaScript", "Go", "Java", "Ruby", "HTTPie", "curl", "PowerShell").
 */
export function GenerateCode(req: model$0.Request, language: string): $CancellablePromise<string> {
    return $Call.ByID(3048321535, req, language);
}

/**
 * ToCurl generates a curl command for the given request.
 */
export function ToCurl(req: model$0.Request): $CancellablePromise<string> {
    return $Call.ByID(1304697822, req);
}
