// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HistoryService exposes request history to the Wails GUI.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as history$0 from "../history/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * Diff returns a text diff between two history entries.
 */
export function Diff(a: history$0.HistoryEntry | null, b: history$0.HistoryEntry | null): $CancellablePromise<string> {
    return $Call.ByID(1091427429, a, b);
}

/**
 * List returns history entries for a given request.
 */
export function List(rootDir: string, req: model$0.Request | null): $CancellablePromise<history$0.HistoryEntry[] | null> {
    return $Call.ByID(1397076562, rootDir, req);
}
