// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ImporterService wraps the importer package for Wails GUI consumption.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * ImportBruno imports a Bruno collection directory.
 */
export function ImportBruno(dir: string, outputDir: string): $CancellablePromise<void> {
    return $Call.ByID(2527261353, dir, outputDir);
}

/**
 * ImportCurl imports a curl command string.
 */
export function ImportCurl(command: string, outputDir: string): $CancellablePromise<void> {
    return $Call.ByID(436656345, command, outputDir);
}

/**
 * ImportInsomnia imports an Insomnia collection export.
 */
export function ImportInsomnia(file: string, outputDir: string): $CancellablePromise<void> {
    return $Call.ByID(784738283, file, outputDir);
}

/**
 * ImportOpenAPI imports an OpenAPI/Swagger spec.
 */
export function ImportOpenAPI(spec: string, outputDir: string): $CancellablePromise<void> {
    return $Call.ByID(2330460541, spec, outputDir);
}

/**
 * ImportPostman imports a Postman collection file into .http files.
 */
export function ImportPostman(file: string, outputDir: string): $CancellablePromise<void> {
    return $Call.ByID(3773169031, file, outputDir);
}
