// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RequestService handles HTTP request execution for the GUI.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * Execute sends an HTTP request with the full pipeline:
 *  1. Resolve environment variables
 *  2. Merge env vars + file-level inline variables
 *  3. Resolve variables in request (URL, headers, body)
 *  4. Load file body if @file reference exists
 *  5. Run pre-request script (if any)
 *  6. Execute HTTP request via engine.ExecuteWithJar
 *  7. Run post-response script (if any)
 *  8. Evaluate assertions
 *  9. Store in chain context for chaining
 *  10. Save to history
 */
export function Execute(req: model$0.Request, envName: string): $CancellablePromise<model$0.Response | null> {
    return $Call.ByID(4137101798, req, envName);
}

/**
 * GetChainVariables returns the names of requests whose responses are stored
 * in the chain context (available for {{name.response.body.field}} syntax).
 */
export function GetChainVariables(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1909787);
}

/**
 * ResolvePreview resolves all variables in the request WITHOUT sending it.
 * Shows what the final URL, headers and body would look like.
 */
export function ResolvePreview(req: model$0.Request, envName: string): $CancellablePromise<model$0.Request | null> {
    return $Call.ByID(1941970655, req, envName);
}

/**
 * SetRootDir sets the collection root directory.
 */
export function SetRootDir(dir: string): $CancellablePromise<void> {
    return $Call.ByID(3985876216, dir);
}
